import Sidebar from "@components/navigation/sidebar";
import Container from "./container";
import Head from 'next/head'
import Navbar from '@components/navigation/navbar'
import {
    FolderIcon,
    HomeIcon,
    TagIcon,
    UsersIcon,
} from '@heroicons/react/outline'
import { useEffect, useState } from "react";
import Loader from "./loader";
import useApp from "@data/hooks/UseApp";
import { useTheme } from "next-themes";


const navigation = [
    { name: 'Inicío', href: '/', icon: HomeIcon },
    { name: 'Produtos', href: '/produto', icon: FolderIcon },
    { name: 'Categorias', href: '/categoria', icon: TagIcon },
    { name: 'Clientes', href: '/cliente', icon: UsersIcon },
]

export default function Shell(props) {
    const [sidebarOpen, setSidebarOpen] = useState(false)
    const { setTheme } = useTheme();
    const { shop: loja } = useApp()

    useEffect(() => { setTheme(loja?.colorTheme) , [] })

    return (
        <>
            <Head>
                <title>{`Next-admin - ${props.title}`}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Loader>
                <div className="h-screen flex overflow-hidden 
                bg-gray-50 dark:bg-warmGray-900 text-gray-900 dark:text-trueGray-100"
                >
                    <Sidebar
                        navigation={navigation}
                        sidebarOpen={sidebarOpen}
                        setSidebarOpen={setSidebarOpen}
                    />
                    <div className="flex flex-col w-0 flex-1 overflow-hidden">

                        <Navbar
                            sidebarOpen={sidebarOpen}
                            setSidebarOpen={setSidebarOpen}
                        />
                        <Container title={props.title}>
                            {props.children}
                        </Container>

                    </div>
                </div>
            </Loader>
        </>
    )
}
